[nextest-filtering] better error reporting for invalid escapes
Previously we'd report something like

  error: expected close parenthesis
   ╭────
 1 │ package(nexte\$)
   ·              ▲
   ·              ╰── missing `)`
   ╰────

  error: expected end of expression
   ╭────
 1 │ package(nexte\$)
   ·              ─┬─
   ·               ╰── unparsed input
   ╰────

Now, we report:

  error: invalid escape character
   ╭────
 1 │ package(nexte\$)
   ·              ─┬
   ·               ╰── invalid escape character
   ╰────